server:
  port: 8080

spring:
  application:
    name:gateway
  cloud:
    gateway:
      routes:
        - id: manage-books-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/book/**
        - id: manage-bookings-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/users/**
        - id: manage-users-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/users/**
        - id: authentication-service
          uri: http://localhost:8090/
          predicates:
            - Path=/login/**