server:
  port: 8080

spring:
  application:
    name:gateway
  cloud:
    gateway:
      routes:
        - id: bookService
          uri: http://localhost:8081/
          predicates:
            - Path=/book/**
        - id: customerService
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**